---
title: promise基础(2)-setTimeout
draft: true
---

import CodeBlock from '@theme/CodeBlock'
import Tabs from '@theme/Tabs'
import TabItem from '@theme/TabItem'

:::tip

文章来源: https://juejin.cn/post/6844904077537574919#heading-9

:::

Promise 结合 setTimeout

### 1

```ts
console.log('start')
setTimeout(() => {
    console.log('time')
})
Promise.resolve().then(() => {
    console.log('resolve')
})
console.log('end')
```

output:

```
start
end
resolve
time
```

### 2

```ts
const promise = new Promise((resolve, reject) => {
    console.log(1)

    setTimeout(() => {
        console.log('timerStart')
        resolve('success')
        console.log('timerEnd')
    }, 0)

    console.log(2)
})

promise.then((res) => {
    console.log(res)
})

console.log(4)
```

output:

```
1
2
4
timerStart
timerEnd
success
```

注意点就是在 promise.then() 的时候，因为 resovle 实在宏任务里面，还未执行，所以此时的状态还是为 pending，暂时不执行

### 3 - 1

```ts
setTimeout(() => {
    console.log('timer1')
    setTimeout(() => {
        console.log('timer3')
    }, 0)
}, 0)
setTimeout(() => {
    console.log('timer2')
}, 0)
console.log('start')
```

output:

```js
start
timer1
timer2
timer3
```

### 3 - 2

```ts
setTimeout(() => {
    console.log('timer1')
    Promise.resolve().then(() => {
        console.log('promise')
    })
}, 0)
setTimeout(() => {
    console.log('timer2')
}, 0)
console.log('start')
```

output:

```js
start
timer1
promise
timer2
```

### 4

```ts
Promise.resolve().then(() => {
    console.log('promise1')
    const timer2 = setTimeout(() => {
        console.log('timer2')
    }, 0)
})
const timer1 = setTimeout(() => {
    console.log('timer1')
    Promise.resolve().then(() => {
        console.log('promise2')
    })
}, 0)
console.log('start')
```

output:

```
start
promise1
timer1
promise2
timer2
```

### 5

```ts
const promise1 = new Promise((resolve, reject) => {
    setTimeout(() => {
        resolve('success')
    }, 1000)
})

const promise2 = promise1.then(() => {
    throw new Error('error!!!')
})

console.log('promise1', promise1)
console.log('promise2', promise2)

setTimeout(() => {
    console.log('promise1', promise1)
    console.log('promise2', promise2)
}, 2000)
```

output:

```
promise1: pending
promise2: pending

throw Error: error!!!

fulfilled: success
rejected: error!!!
```

这里要注意执行完两个 pending 之后，紧接着就是微任务的 `throw new Error` ，会执行一个报错

### 6

```ts
const promise1 = new Promise((resolve, reject) => {
    setTimeout(() => {
        resolve('success')
        console.log('timer1')
    }, 1000)
    console.log('promise1里的内容')
})

const promise2 = promise1.then(() => {
    throw new Error('error!!!')
})

console.log('promise1', promise1)
console.log('promise2', promise2)

setTimeout(() => {
    console.log('timer2')
    console.log('promise1', promise1)
    console.log('promise2', promise2)
}, 2000)
```

output:

```
promise1里的内容
promise1 pending
promise2 pending
timer1
new Error('error!!!')
timer2
fulfilled success
promise2 error!!!
```

这里可以理解为先执行两个还没结果的 pending, 等到执行 `promise1.then()` 的时候，因为还在 pending, 所以不会执行 `throw new Error` 代码
所以现在有两个宏任务定时器，间隔 1 秒后，执行 `resolve` ，所以 `then()` 可以继续执行了，也就是先输出 timer1 然后 throw
